version: '3'

volumes:
  rc_postgres_data: {}
  rc_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: rc_django
    container_name: rc_django
    restart: always
    depends_on:
      - postgres
    volumes:
      - .:/app
    env_file:
      - ./.envs_example/.django
      - ./.envs_example/.postgres
    ports:
      - "80:80"

  postgres:
    image: postgres:15
    container_name: rc_postgres
    restart: always
    volumes:
      - rc_postgres_data:/var/lib/postgresql/data
      - rc_postgres_data_backups:/backups
    ports:
      - "5432:5432"
    env_file:
      - ./.envs_example/.postgres
