#!/bin/sh

set -o errexit
set -o nounset

postgres_ready() {
python << END
import sys

import psycopg2

try:
    psycopg2.connect(
        dbname="${POSTGRES_DB}",
        user="${POSTGRES_USER}",
        password="${POSTGRES_PASSWORD}",
        host="${POSTGRES_HOST}",
        port="${POSTGRES_PORT}",
    )
except psycopg2.OperationalError:
    sys.exit(-1)
sys.exit(0)

END
}

until postgres_ready; do
  >&2 echo 'Waiting for PostgreSQL to become available...'
  sleep 1
done
>&2 echo 'PostgreSQL is available'


prepare_database() {
  python manage.py makemigrations
  python manage.py migrate
}

prepare_database


prepare_django() {
  python manage.py collectstatic --noinput
  python manage.py loaddata ./.fixtures/users.json
  python manage.py loaddata ./.fixtures/currencies.json
}

prepare_django


prepare_cron() {
  touch /var/log/cron.log
  printenv | grep -Ev 'BASHOPTS|BASH_VERSINFO|EUID|PPID|SHELLOPTS|UID|LANG|PWD|GPG_KEY|_=' >> /etc/environment

  python manage.py crontab remove
  python manage.py crontab add
  service cron start
}

prepare_cron


exec /usr/local/bin/gunicorn config.asgi --bind 0.0.0.0:80 --chdir=/app -k uvicorn.workers.UvicornWorker
