# Generated by Django 5.1.6 on 2025-02-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AlterField(
            model_name='price',
            name='unit_amount',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
