# Generated by Django 5.1.6 on 2025-03-04 13:29

import django.db.models.deletion
from django.db import migrations, models


def create_currencies(apps, schema_editor):
    Currency = apps.get_model("items", "Currency")
    Price = apps.get_model("items", "Price")

    for currency in Price.objects.all().values_list('currency', flat=True).distinct():
        Currency.objects.create(name_iso=currency)


def reverse_create_currencies(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_paymentsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name_iso', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=30)),
                ('symbol', models.CharField(blank=True, default='', max_length=10)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'currency',
            },
        ),
        migrations.RunPython(
            create_currencies, reverse_create_currencies
        ),
        migrations.AlterField(
            model_name='price',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='items.currency'),
        ),
    ]
